# Generated by Django 4.1.2 on 2022-10-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professore',
            new_name='Professores',
        ),
    ]
